library(insuranceSimModel)
context("Test Allocate Policies To Month")

concenEqual <- rep(1, 12) / 12
concenQuarters <- rep(c(0.25, 0, 0), 4)
concenDescending <- 12:1 / sum(12:1)

test_that("allocatePoliciesToMonth is a vector of length 12",{
     expect_that(length(allocatePoliciesToMonth(100)), equals(12))
     expect_that(length(allocatePoliciesToMonth(12)), equals(12))
     expect_that(length(allocatePoliciesToMonth(5)), equals(12))
     expect_that(length(allocatePoliciesToMonth(0)), equals(12))
     expect_that(length(allocatePoliciesToMonth(100, concenEqual)), equals(12))
     expect_that(length(allocatePoliciesToMonth(100, concenQuarters)), equals(12))
     expect_that(length(allocatePoliciesToMonth(100, concenDescending)), equals(12))
     expect_that(length(allocatePoliciesToMonth(12, concenEqual)), equals(12))
     expect_that(length(allocatePoliciesToMonth(12, concenQuarters)), equals(12))
     expect_that(length(allocatePoliciesToMonth(12, concenDescending)), equals(12))
     expect_that(length(allocatePoliciesToMonth(5, concenEqual)), equals(12))
     expect_that(length(allocatePoliciesToMonth(5, concenQuarters)), equals(12))
     expect_that(length(allocatePoliciesToMonth(5, concenDescending)), equals(12))
     expect_that(length(allocatePoliciesToMonth(0, concenEqual)), equals(12))
     expect_that(length(allocatePoliciesToMonth(0, concenQuarters)), equals(12))
     expect_that(length(allocatePoliciesToMonth(0, concenDescending)), equals(12))

})

test_that("allocatePoliciesToMonth total input", {
     expect_that(sum(allocatePoliciesToMonth(100)), equals(100))
     expect_that(sum(allocatePoliciesToMonth(12)), equals(12))
     expect_that(sum(allocatePoliciesToMonth(5)), equals(5))
     expect_that(sum(allocatePoliciesToMonth(0)), equals(0))
     expect_that(sum(allocatePoliciesToMonth(100, concenEqual)), equals(100))
     expect_that(sum(allocatePoliciesToMonth(100, concenQuarters)), equals(100))
     expect_that(sum(allocatePoliciesToMonth(100, concenDescending)), equals(100))
     expect_that(sum(allocatePoliciesToMonth(12, concenEqual)), equals(12))
     expect_that(sum(allocatePoliciesToMonth(12, concenQuarters)), equals(12))
     expect_that(sum(allocatePoliciesToMonth(12, concenDescending)), equals(12))
     expect_that(sum(allocatePoliciesToMonth(5, concenEqual)), equals(5))
     expect_that(sum(allocatePoliciesToMonth(5, concenQuarters)), equals(5))
     expect_that(sum(allocatePoliciesToMonth(5, concenDescending)), equals(5))
     expect_that(sum(allocatePoliciesToMonth(0, concenEqual)), equals(0))
     expect_that(sum(allocatePoliciesToMonth(0, concenQuarters)), equals(0))
     expect_that(sum(allocatePoliciesToMonth(0, concenDescending)), equals(0))
})
